name: local_package
description: A simple Flutter app using a local package for food UI.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  food_ui:
    path: packages/food_ui

flutter:
  uses-material-design: true
